<div id="mainTitle-wrapper">
    <div id="mainTitle-container">
        <div class="row">
        </div>
        <div class="row">
            <div class="col-12">
                <h1>
                    CARD<br/>
                    MEM<img src="<?= $this->basePath('img/oclock.png') ?>" style="height: 60px;margin-bottom: 15px;" />RY<br/>
                    Match
                </h1>
                <button type="button" class="btn btn-primary mt-5" onclick="startNewGame('<?= $this->url('play', [], ['force_canonical' => true]) ?>')">Démarer une nouvelle partie</button>
            </div>
        </div>
    </div>
</div>