<div id="mainTitle-wrapper">
    <div id="mainTitle-container">
        <h1>
            CARD<br/>
            MEM<img src="<?= $this->basePath('img/oclock.png') ?>" style="height: 60px;margin-bottom: 15px;"/>RY<br/>
            Match
        </h1>
        <div class="middle-container">
            <div class="scoreboard">
                <div class="scoreboard-title">Tableau des scores</div>
                <div class="scoreboard-container"></div>
            </div>

            <button type="button" class="btn btn-primary mt-5" onclick="startNewGame()">Démarer une nouvelle
                partie
            </button>
        </div>
    </div>
</div>

<?php $this->inlineScript()->prependFile($this->basePath('js/mainMenu.js')) ?>
